import type { ContextRecord, SearchResult } from '@/types';

export const mockEvents: ContextRecord[] = [
  {
    eventId: 'evt-001',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'main',
    feature: 'FlowSync initialization',
    decision: null,
    tasks: ['Set up project structure', 'Configure CI/CD pipeline'],
    stage: 'Setup',
    risk: null,
    confidence: 85,
    entities: ['.flowsync.json', 'copilot-instructions.md'],
    author: 'aahil-khan',
    commitHash: '588f888',
    extractedAt: '2026-03-01T10:00:00Z',
  },
  {
    eventId: 'evt-002',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'main',
    feature: 'Task Manager',
    decision: null,
    tasks: ['Add error handling', 'Add unit tests', 'Integrate with event pipeline'],
    stage: 'Feature Development',
    risk: null,
    confidence: 80,
    entities: ['main.py', 'TaskManager', 'event_pipeline.py'],
    author: 'aahil-khan',
    commitHash: '610eb72',
    extractedAt: '2026-03-01T12:30:00Z',
  },
  {
    eventId: 'evt-003',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'main',
    feature: 'Auth pipeline',
    decision: 'Used scrypt KDF over bcrypt for token hashing due to configurable memory hardness',
    tasks: ['Implement token verification', 'Add timing-safe comparison'],
    stage: 'Feature Development',
    risk: 'Token logged in plaintext in debug mode',
    confidence: 90,
    entities: ['auth.py', 'ingestion/index.js', 'scrypt'],
    author: 'aahil-khan',
    commitHash: 'a3c9f01',
    extractedAt: '2026-03-01T14:15:00Z',
  },
  {
    eventId: 'evt-004',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'main',
    feature: 'Event ingestion',
    decision: 'Fire-and-forget async invoke for AI processing to avoid blocking ingestion',
    tasks: ['Refactor Lambda invocation pattern', 'Add DLQ for failed processing'],
    stage: 'Refactoring',
    risk: null,
    confidence: 88,
    entities: ['ingestion/index.js', 'ai_processing/handler.py', 'Lambda'],
    author: 'aahil-khan',
    commitHash: 'c72d1e5',
    extractedAt: '2026-03-01T16:00:00Z',
  },
  {
    eventId: 'evt-005',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'feature/dashboard',
    feature: 'Dashboard UI',
    decision: null,
    tasks: ['Create timeline view', 'Add context cards', 'Implement search page'],
    stage: 'Feature Development',
    risk: 'No error handling on API calls',
    confidence: 75,
    entities: ['App.tsx', 'Dashboard.tsx', 'ContextCard.tsx'],
    author: 'aahil-khan',
    commitHash: 'f89ab23',
    extractedAt: '2026-03-01T18:45:00Z',
  },
  {
    eventId: 'evt-006',
    projectId: '28c3fad3-4cbd-414e-bb63-fcc559ea238b',
    branch: 'main',
    feature: 'Unit tests',
    decision: null,
    tasks: ['Add integration tests for query Lambda', 'Add mock DynamoDB tests'],
    stage: 'Testing',
    risk: null,
    confidence: 92,
    entities: ['test_query.py', 'test_ingestion.js', 'jest.config.js'],
    author: 'aahil-khan',
    commitHash: 'd45ef67',
    extractedAt: '2026-03-02T09:00:00Z',
  },
];

export const mockSearchResult: SearchResult = {
  answer:
    'The task manager was added to handle async job scheduling for the event pipeline. It integrates with the ingestion Lambda to process events asynchronously using a fire-and-forget pattern. The implementation uses scrypt KDF for token authentication and writes context records to DynamoDB after AI extraction via Bedrock.',
  answerGrounded: true,
  sources: [
    {
      commitHash: '610eb72',
      feature: 'Task Manager',
      extractedAt: '2026-03-01T12:30:00Z',
      relevanceScore: 98.2,
    },
    {
      commitHash: '588f888',
      feature: 'FlowSync initialization',
      extractedAt: '2026-03-01T10:00:00Z',
      relevanceScore: 87.1,
    },
    {
      commitHash: 'a3c9f01',
      feature: 'Auth pipeline',
      extractedAt: '2026-03-01T14:15:00Z',
      relevanceScore: 72.4,
    },
  ],
};
